// This guess the number game is a short TypeScript/Node.js project that allows the user to guess the number generated by the computer. There are also several ways to alter the game, like adding more rounds or displaying the score. It’s quite simple and uses the random function to generate a number.
console.log("Number Guessing Game");
import inquirer from "inquirer";
let num = Math.floor(Math.random() * 10);
let uans = await inquirer.prompt({
  type: "number",
  name: "guess",
  message: "Guess the number between 1 to 10",
});
while (uans.guess !== num) {
  uans = await inquirer.prompt({
    type: "number",
    name: "guess",
    message: "Guess the number again",
  });
  if (uans.guess === num) {
    console.log("right");
  } else {
    console.log("wrong");
  }
}
